Repository dnd-side-project/dnd-10th-9-backend, pull requests merged in 2024-02, with the labels that each got.

#4 feat(#2) : 엔티티 작성
  src/main/java/com/dnd/dotchi/DotchiApplication.java
  src/main/java/com/dnd/dotchi/domain/blacklist/entity/BlackList.java
  src/main/java/com/dnd/dotchi/domain/card/entity/Card.java
  src/main/java/com/dnd/dotchi/domain/card/entity/Comment.java
  src/main/java/com/dnd/dotchi/domain/card/entity/Theme.java
  src/main/java/com/dnd/dotchi/domain/card/entity/TodayCard.java
  src/main/java/com/dnd/dotchi/domain/common/BaseEntity.java
  src/main/java/com/dnd/dotchi/domain/member/entity/Member.java
  src/main/java/com/dnd/dotchi/domain/report/entity/Report.java
  src/main/java/com/dnd/nine/NineApplication.java
  src/test/java/com/dnd/dotchi/DotchiApplicationTests.java
Labels: 개발

#8 application.yml 설정 파일 작성
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: 개발

#10 Swagger 초기 설정
  build.gradle
  src/main/java/com/dnd/dotchi/global/config/OpenAPIConfig.java
Labels: 개발

#11 예외 초기 틀 잡기
  src/main/java/com/dnd/dotchi/global/exception/BadRequestException.java
  src/main/java/com/dnd/dotchi/global/exception/BaseException.java
  src/main/java/com/dnd/dotchi/global/exception/ErrorResponse.java
  src/main/java/com/dnd/dotchi/global/exception/ExceptionResponse.java
  src/main/java/com/dnd/dotchi/global/exception/ExceptionType.java
  src/main/java/com/dnd/dotchi/global/exception/GlobalExceptionHandler.java
  src/main/java/com/dnd/dotchi/global/exception/NotFoundException.java
Labels: 개발

#13 Querydsl 초기 설정
  build.gradle
  src/main/java/com/dnd/dotchi/domain/member/entity/Member.java
  src/main/java/com/dnd/dotchi/global/config/QuerydslConfig.java
Labels: 개발

#15 Swagger request에 이미지 넣을 수 있도록 설정
  src/main/java/com/dnd/dotchi/global/config/SwaggerBeanConfig.java
Labels: 개발

#19 feat : (#17) 카드 요청 DTO 푸쉬
  src/main/java/com/dnd/dotchi/domain/card/dto/request/CardsByThemeRequest.java
Labels: 개발

#21 [DEV] 카드 작성 기능 구현
  .gitignore
  src/main/java/com/dnd/dotchi/domain/card/controller/CardController.java
  src/main/java/com/dnd/dotchi/domain/card/controller/CardControllerDocs.java
  src/main/java/com/dnd/dotchi/domain/card/dto/request/CardsWriteRequest.java
  src/main/java/com/dnd/dotchi/domain/card/dto/response/CardsByThemeResponse.java
  src/main/java/com/dnd/dotchi/domain/card/dto/response/CardsWriteResponse.java
  src/main/java/com/dnd/dotchi/domain/card/dto/response/resultinfo/CardsByThemeRequestResultType.java
  src/main/java/com/dnd/dotchi/domain/card/dto/response/resultinfo/CardsRequestResultType.java
  src/main/java/com/dnd/dotchi/domain/card/entity/Card.java
  src/main/java/com/dnd/dotchi/domain/card/exception/CardExceptionType.java
  src/main/java/com/dnd/dotchi/domain/card/exception/ThemeExceptionType.java
  src/main/java/com/dnd/dotchi/domain/card/repository/CardRepository.java
  src/main/java/com/dnd/dotchi/domain/card/repository/ThemeRepository.java
  src/main/java/com/dnd/dotchi/domain/card/service/CardService.java
  src/main/java/com/dnd/dotchi/domain/member/exception/MemberExceptionType.java
  src/main/java/com/dnd/dotchi/domain/member/repository/MemberRepository.java
  src/main/java/com/dnd/dotchi/infra/image/ImageUploader.java
  src/main/resources/application.yml
  src/test/java/com/dnd/dotchi/domain/card/controller/CardControllerTest.java
  src/test/java/com/dnd/dotchi/domain/card/repository/CardRepositoryTest.java
  src/test/java/com/dnd/dotchi/domain/card/service/CardServiceTest.java
  src/test/resources/application.yml
Labels: 개발

#22 [DEV] 댓글 작성 기능 구현
  src/main/java/com/dnd/dotchi/DotchiApplication.java
  src/main/java/com/dnd/dotchi/domain/card/controller/CardController.java
  src/main/java/com/dnd/dotchi/domain/card/controller/CardControllerDocs.java
  src/main/java/com/dnd/dotchi/domain/card/dto/response/WriteCommentOnCardResponse.java
  src/main/java/com/dnd/dotchi/domain/card/dto/response/resultinfo/CardsRequestResultType.java
  src/main/java/com/dnd/dotchi/domain/card/entity/Card.java
  src/main/java/com/dnd/dotchi/domain/card/entity/TodayCard.java
  src/main/java/com/dnd/dotchi/domain/card/exception/CardExceptionType.java
  src/main/java/com/dnd/dotchi/domain/card/repository/TodayCardRepository.java
  src/main/java/com/dnd/dotchi/domain/card/service/CardService.java
  src/test/java/com/dnd/dotchi/domain/card/controller/CardControllerTest.java
  src/test/java/com/dnd/dotchi/domain/card/entity/CardTest.java
  src/test/java/com/dnd/dotchi/domain/card/entity/TodayCardTest.java
  src/test/java/com/dnd/dotchi/domain/card/repository/TodayCardRepositoryTest.java
  src/test/java/com/dnd/dotchi/domain/card/service/CardServiceTest.java
Labels: 개발

#25 [DEV] 전체 카드 조회 기능
  src/main/java/com/dnd/dotchi/domain/card/controller/CardController.java
  src/main/java/com/dnd/dotchi/domain/card/controller/CardControllerDocs.java
  src/main/java/com/dnd/dotchi/domain/card/dto/request/CardsAllRequest.java
  src/main/java/com/dnd/dotchi/domain/card/dto/response/CadsAllResultResponse.java
  src/main/java/com/dnd/dotchi/domain/card/dto/response/CardsAllResponse.java
  src/main/java/com/dnd/dotchi/domain/card/dto/response/RecentCardsAllResponse.java
  src/main/java/com/dnd/dotchi/domain/card/dto/response/resultinfo/CardsRequestResultType.java
  src/main/java/com/dnd/dotchi/domain/card/repository/CardCustomRepository.java
  src/main/java/com/dnd/dotchi/domain/card/repository/CardCustomRepositoryImpl.java
  src/main/java/com/dnd/dotchi/domain/card/service/CardService.java
  src/test/java/com/dnd/dotchi/domain/card/controller/CardControllerTest.java
  src/test/java/com/dnd/dotchi/domain/card/repository/CardRepositoryTest.java
Labels: 개발

#26 댓글 증가 동기화 처리 부분에서 재시도 로직 및 테스트 구현
  build.gradle
  src/main/java/com/dnd/dotchi/DotchiApplication.java
  src/main/java/com/dnd/dotchi/domain/card/entity/Card.java
  src/main/java/com/dnd/dotchi/domain/card/entity/TodayCard.java
  src/main/java/com/dnd/dotchi/domain/card/exception/CardExceptionType.java
  src/main/java/com/dnd/dotchi/domain/card/service/CardService.java
  src/main/java/com/dnd/dotchi/global/config/AppConfig.java
  src/main/java/com/dnd/dotchi/global/config/JpaConfig.java
  src/main/java/com/dnd/dotchi/global/exception/GlobalExceptionHandler.java
  src/main/java/com/dnd/dotchi/global/exception/RetryLimitExceededException.java
  src/test/java/com/dnd/dotchi/domain/card/entity/CardTest.java
  src/test/java/com/dnd/dotchi/domain/card/entity/TodayCardTest.java
  src/test/java/com/dnd/dotchi/domain/card/service/CardServiceTest.java
Labels: 개발

#29 [DEV] 회원 정보 조회 기능 구현
  src/main/java/com/dnd/dotchi/domain/card/controller/CardController.java
  src/main/java/com/dnd/dotchi/domain/card/controller/CardControllerDocs.java
  src/main/java/com/dnd/dotchi/domain/card/dto/response/RecentCardsAllResponse.java
  src/main/java/com/dnd/dotchi/domain/card/dto/response/RecentCardsByThemeResponse.java
  src/main/java/com/dnd/dotchi/domain/card/entity/Card.java
  src/main/java/com/dnd/dotchi/domain/card/repository/CardCustomRepository.java
  src/main/java/com/dnd/dotchi/domain/card/repository/CardCustomRepositoryImpl.java
  src/main/java/com/dnd/dotchi/domain/member/controller/MemberController.java
  src/main/java/com/dnd/dotchi/domain/member/controller/MemberControllerDocs.java
  src/main/java/com/dnd/dotchi/domain/member/dto/request/MemberInfoRequest.java
  src/main/java/com/dnd/dotchi/domain/member/dto/response/MemberInfoResponse.java
  src/main/java/com/dnd/dotchi/domain/member/dto/response/MemberInfoResultResponse.java
  src/main/java/com/dnd/dotchi/domain/member/dto/response/MemberResponse.java
  src/main/java/com/dnd/dotchi/domain/member/dto/response/RecentCardsByMemberResponse.java
  src/main/java/com/dnd/dotchi/domain/member/dto/response/resultinfo/MemberRequestResultType.java
  src/main/java/com/dnd/dotchi/domain/member/service/MemberService.java
  src/test/java/com/dnd/dotchi/domain/card/controller/CardControllerTest.java
  src/test/java/com/dnd/dotchi/domain/card/repository/CardRepositoryTest.java
  src/test/java/com/dnd/dotchi/domain/card/service/CardServiceTest.java
  src/test/java/com/dnd/dotchi/domain/member/controller/MemberControllerTest.java
  src/test/java/com/dnd/dotchi/domain/member/service/MemberServiceTest.java
Labels: 개발

#31 [DEV] 신고하기 기능 구현
  src/main/java/com/dnd/dotchi/domain/card/dto/response/CardsByThemeResponse.java
  src/main/java/com/dnd/dotchi/domain/card/dto/response/CardsWriteResponse.java
  src/main/java/com/dnd/dotchi/domain/card/dto/response/WriteCommentOnCardResponse.java
  src/main/java/com/dnd/dotchi/domain/card/service/CardService.java
  src/main/java/com/dnd/dotchi/domain/member/controller/MemberController.java
  src/main/java/com/dnd/dotchi/domain/report/controller/ReportController.java
  src/main/java/com/dnd/dotchi/domain/report/controller/ReportControllerDocs.java
  src/main/java/com/dnd/dotchi/domain/report/dto/response/ReportResponse.java
  src/main/java/com/dnd/dotchi/domain/report/dto/response/resultinfo/ReportRequestResultType.java
  src/main/java/com/dnd/dotchi/domain/report/repository/ReportRepository.java
  src/main/java/com/dnd/dotchi/domain/report/request/ReportRequest.java
  src/main/java/com/dnd/dotchi/domain/report/service/ReportService.java
  src/test/java/com/dnd/dotchi/domain/card/controller/CardControllerTest.java
  src/test/java/com/dnd/dotchi/domain/report/controller/ReportControllerTest.java
  src/test/java/com/dnd/dotchi/domain/report/service/ReportServiceTest.java
Labels: 개발

#35 [DEV] 카드 삭제하기 기능 구현
  src/main/java/com/dnd/dotchi/domain/card/controller/CardController.java
  src/main/java/com/dnd/dotchi/domain/card/controller/CardControllerDocs.java
  src/main/java/com/dnd/dotchi/domain/card/dto/response/DeleteCardResponse.java
  src/main/java/com/dnd/dotchi/domain/card/dto/response/resultinfo/CardsRequestResultType.java
  src/main/java/com/dnd/dotchi/domain/card/service/CardService.java
  src/test/java/com/dnd/dotchi/domain/card/controller/CardControllerTest.java
  src/test/java/com/dnd/dotchi/domain/card/service/CardServiceTest.java
  src/test/resources/data.sql
Labels: 개발

#33 [DEV] 차단하기 기능 구현
  src/main/java/com/dnd/dotchi/domain/blacklist/controller/BlacklistController.java
  src/main/java/com/dnd/dotchi/domain/blacklist/controller/BlacklistControllerDocs.java
  src/main/java/com/dnd/dotchi/domain/blacklist/dto/request/BlockRequest.java
  src/main/java/com/dnd/dotchi/domain/blacklist/dto/response/BlockResponse.java
  src/main/java/com/dnd/dotchi/domain/blacklist/dto/response/resulltinfo/BlockRequestResultType.java
  src/main/java/com/dnd/dotchi/domain/blacklist/repository/BlackListRepository.java
  src/main/java/com/dnd/dotchi/domain/blacklist/service/BlacklistService.java
  src/test/java/com/dnd/dotchi/domain/blacklist/controller/BlacklistControllerTest.java
  src/test/java/com/dnd/dotchi/domain/blacklist/service/BlacklistServiceTest.java
  src/test/java/com/dnd/dotchi/domain/card/repository/TodayCardRepositoryTest.java
  src/test/java/com/dnd/dotchi/domain/report/service/ReportServiceTest.java
Labels: 개발

#37 [DEV] 카드 댓글 조회 기능 구현
  src/main/java/com/dnd/dotchi/domain/card/controller/CardController.java
  src/main/java/com/dnd/dotchi/domain/card/controller/CardControllerDocs.java
  src/main/java/com/dnd/dotchi/domain/card/dto/response/CadsAllResultResponse.java
  src/main/java/com/dnd/dotchi/domain/card/dto/response/CardsResponse.java
  src/main/java/com/dnd/dotchi/domain/card/dto/response/CommentResultResponse.java
  src/main/java/com/dnd/dotchi/domain/card/dto/response/CommentsResponse.java
  src/main/java/com/dnd/dotchi/domain/card/dto/response/GetCommentOnCardResponse.java
  src/main/java/com/dnd/dotchi/domain/card/dto/response/resultinfo/CardsRequestResultType.java
  src/main/java/com/dnd/dotchi/domain/card/repository/CommentRepository.java
  src/main/java/com/dnd/dotchi/domain/card/service/CardService.java
  src/test/java/com/dnd/dotchi/domain/card/controller/CardControllerTest.java
  src/test/java/com/dnd/dotchi/domain/card/service/CardServiceTest.java
  src/test/resources/data.sql
Labels: 개발

#39 [DEV] 메인 홈페이지 조회 기능
  src/main/java/com/dnd/dotchi/domain/card/controller/CardController.java
  src/main/java/com/dnd/dotchi/domain/card/controller/CardControllerDocs.java
  src/main/java/com/dnd/dotchi/domain/card/dto/response/CardsResponse.java
  src/main/java/com/dnd/dotchi/domain/card/dto/response/CommentResultResponse.java
  src/main/java/com/dnd/dotchi/domain/card/dto/response/CommentsResponse.java
  src/main/java/com/dnd/dotchi/domain/card/dto/response/HomePageResponse.java
  src/main/java/com/dnd/dotchi/domain/card/dto/response/HomePageResultResponse.java
  src/main/java/com/dnd/dotchi/domain/card/dto/response/RecentCardsOnHomeResponse.java
  src/main/java/com/dnd/dotchi/domain/card/dto/response/ThemesOnHomeResponse.java
  src/main/java/com/dnd/dotchi/domain/card/dto/response/TodayCardsOnHomeResponse.java
  src/main/java/com/dnd/dotchi/domain/card/dto/response/resultinfo/CardsRequestResultType.java
  src/main/java/com/dnd/dotchi/domain/card/repository/CardRepository.java
  src/main/java/com/dnd/dotchi/domain/card/repository/TodayCardRepository.java
  src/main/java/com/dnd/dotchi/domain/card/service/CardService.java
  src/test/java/com/dnd/dotchi/domain/card/controller/CardControllerTest.java
  src/test/java/com/dnd/dotchi/domain/card/repository/CardRepositoryTest.java
  src/test/java/com/dnd/dotchi/domain/card/service/CardServiceTest.java
  src/test/resources/data.sql
Labels: 개발

#41 [DEV] 로그인 기능 구현 및 이미 구현한 모든 기능에서 토큰으로 전달받은 회원 정보를 통해 동작하도록 개선
  build.gradle
  src/main/java/com/dnd/dotchi/domain/blacklist/controller/BlacklistController.java
  src/main/java/com/dnd/dotchi/domain/blacklist/controller/BlacklistControllerDocs.java
  src/main/java/com/dnd/dotchi/domain/blacklist/dto/request/BlockRequest.java
  src/main/java/com/dnd/dotchi/domain/blacklist/service/BlacklistService.java
  src/main/java/com/dnd/dotchi/domain/card/controller/CardController.java
  src/main/java/com/dnd/dotchi/domain/card/controller/CardControllerDocs.java
  src/main/java/com/dnd/dotchi/domain/card/dto/request/CardsWriteRequest.java
  src/main/java/com/dnd/dotchi/domain/card/entity/Theme.java
  src/main/java/com/dnd/dotchi/domain/card/exception/CardExceptionType.java
  src/main/java/com/dnd/dotchi/domain/card/repository/CommentRepository.java
  src/main/java/com/dnd/dotchi/domain/card/service/CardService.java
  src/main/java/com/dnd/dotchi/domain/member/controller/MemberController.java
  src/main/java/com/dnd/dotchi/domain/member/controller/MemberControllerDocs.java
  src/main/java/com/dnd/dotchi/domain/member/dto/request/MemberAuthorizationRequest.java
  src/main/java/com/dnd/dotchi/domain/member/dto/response/MemberAuthorizationResponse.java
  src/main/java/com/dnd/dotchi/domain/member/dto/response/MemberAuthorizationResultResponse.java
  src/main/java/com/dnd/dotchi/domain/member/dto/response/resultinfo/MemberRequestResultType.java
  src/main/java/com/dnd/dotchi/domain/member/exception/AuthExceptionType.java
  src/main/java/com/dnd/dotchi/domain/member/service/MemberService.java
  src/main/java/com/dnd/dotchi/domain/report/controller/ReportController.java
  src/main/java/com/dnd/dotchi/domain/report/controller/ReportControllerDocs.java
  src/main/java/com/dnd/dotchi/domain/report/request/ReportRequest.java
  src/main/java/com/dnd/dotchi/domain/report/service/ReportService.java
  src/main/java/com/dnd/dotchi/global/config/OpenAPIConfig.java
  src/main/java/com/dnd/dotchi/global/config/WebMvcConfig.java
  src/main/java/com/dnd/dotchi/global/jwt/Auth.java
  src/main/java/com/dnd/dotchi/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/dnd/dotchi/global/jwt/JwtAuthorizationArgumentResolver.java
  src/main/java/com/dnd/dotchi/global/jwt/TokenPayload.java
  src/main/java/com/dnd/dotchi/global/jwt/TokenProcessor.java
  src/main/resources/application.yml
  src/test/java/com/dnd/dotchi/domain/blacklist/controller/BlacklistControllerTest.java
  src/test/java/com/dnd/dotchi/domain/blacklist/service/BlacklistServiceTest.java
  src/test/java/com/dnd/dotchi/domain/card/controller/CardControllerTest.java
  src/test/java/com/dnd/dotchi/domain/card/service/CardServiceTest.java
  src/test/java/com/dnd/dotchi/domain/member/controller/MemberControllerTest.java
  src/test/java/com/dnd/dotchi/domain/member/service/MemberServiceTest.java
  src/test/java/com/dnd/dotchi/domain/report/controller/ReportControllerTest.java
  src/test/java/com/dnd/dotchi/domain/report/service/ReportServiceTest.java
  src/test/java/com/dnd/dotchi/test/ControllerTest.java
  src/test/resources/application.yml
  src/test/resources/data.sql
Labels: 개발

#45 Prod와 Test 코드의 data.sql 분리 및 헬스 체크 API 추가
  .gitignore
  src/main/java/com/dnd/dotchi/domain/healthcheck/controller/HealthCheckController.java
  src/main/java/com/dnd/dotchi/domain/healthcheck/controller/HealthCheckControllerDocs.java
  src/main/java/com/dnd/dotchi/domain/healthcheck/service/HealthCheckService.java
  src/main/resources/application.yml
  src/main/resources/data-prod.sql
  src/main/resources/data-test.sql
  src/test/java/com/dnd/dotchi/domain/card/controller/CardControllerTest.java
  src/test/java/com/dnd/dotchi/domain/card/repository/CardRepositoryTest.java
  src/test/java/com/dnd/dotchi/domain/card/service/CardServiceTest.java
  src/test/java/com/dnd/dotchi/domain/member/service/MemberServiceTest.java
  src/test/java/com/dnd/dotchi/domain/report/controller/ReportControllerTest.java
  src/test/resources/application.yml
Labels: 개발

#43 [DEV] 멤버 수정하기 기능 구현
  src/main/java/com/dnd/dotchi/domain/card/dto/request/CardsWriteRequest.java
  src/main/java/com/dnd/dotchi/domain/member/controller/MemberController.java
  src/main/java/com/dnd/dotchi/domain/member/controller/MemberControllerDocs.java
  src/main/java/com/dnd/dotchi/domain/member/dto/request/MemberInfoRequest.java
  src/main/java/com/dnd/dotchi/domain/member/dto/request/MemberModifyRequest.java
  src/main/java/com/dnd/dotchi/domain/member/dto/response/MemberInfoResponse.java
  src/main/java/com/dnd/dotchi/domain/member/dto/response/MemberModifyResponse.java
  src/main/java/com/dnd/dotchi/domain/member/dto/response/resultinfo/MemberRequestResultType.java
  src/main/java/com/dnd/dotchi/domain/member/entity/Member.java
  src/main/java/com/dnd/dotchi/domain/member/service/MemberService.java
  src/main/java/com/dnd/dotchi/global/jwt/JwtAuthenticationFilter.java
  src/main/resources/data-prod.sql
  src/test/java/com/dnd/dotchi/domain/member/controller/MemberControllerTest.java
  src/test/java/com/dnd/dotchi/domain/member/service/MemberServiceTest.java
Labels: 개발

#47 AWS S3를 통해 이미지를 업로드하고 URL 반환받는 기능 구현 및 테스트 이미지 업로드 객체 Mocking
  build.gradle
  src/main/java/com/dnd/dotchi/domain/card/service/CardService.java
  src/main/java/com/dnd/dotchi/domain/member/controller/MemberController.java
  src/main/java/com/dnd/dotchi/domain/member/service/MemberService.java
  src/main/java/com/dnd/dotchi/global/config/S3Config.java
  src/main/java/com/dnd/dotchi/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/dnd/dotchi/infra/image/ImageUploader.java
  src/main/java/com/dnd/dotchi/infra/image/S3FileUploader.java
  src/main/resources/application.yml
  src/test/java/com/dnd/dotchi/domain/card/controller/CardControllerTest.java
  src/test/java/com/dnd/dotchi/domain/card/service/CardServiceTest.java
  src/test/java/com/dnd/dotchi/domain/member/service/MemberServiceTest.java
  src/test/resources/application.yml
Labels: 개발

#49 [BUG] Mysql에서 사용 안하는 sql 문법 수정
  src/main/java/com/dnd/dotchi/domain/card/repository/CardCustomRepository.java
  src/main/java/com/dnd/dotchi/domain/card/repository/CardCustomRepositoryImpl.java
  src/main/java/com/dnd/dotchi/domain/card/repository/CardRepository.java
  src/main/resources/data-prod.sql
  src/test/java/com/dnd/dotchi/domain/member/controller/MemberControllerTest.java
Labels: 버그

#52 회원 정보 수정 시, 프로필 이미지가 빈 파일인지 확인하는 기능 구현
  src/main/java/com/dnd/dotchi/domain/member/service/MemberService.java
  src/test/java/com/dnd/dotchi/domain/member/service/MemberServiceTest.java
Labels: 개발

#56 Bug/#55
  src/main/java/com/dnd/dotchi/domain/blacklist/controller/BlacklistController.java
  src/main/java/com/dnd/dotchi/domain/blacklist/controller/BlacklistControllerDocs.java
  src/main/java/com/dnd/dotchi/domain/blacklist/dto/response/resulltinfo/BlockRequestResultType.java
  src/main/java/com/dnd/dotchi/domain/blacklist/repository/BlackListRepository.java
  src/main/java/com/dnd/dotchi/domain/blacklist/service/BlacklistService.java
  src/main/java/com/dnd/dotchi/domain/card/controller/CardController.java
  src/main/java/com/dnd/dotchi/domain/card/dto/request/CardsAllRequest.java
  src/main/java/com/dnd/dotchi/domain/card/dto/request/CardsByThemeRequest.java
  src/main/java/com/dnd/dotchi/domain/card/dto/response/CommentResultResponse.java
  src/main/java/com/dnd/dotchi/domain/card/dto/response/GetCommentOnCardResponse.java
  src/main/java/com/dnd/dotchi/domain/card/dto/response/ThemesOnHomeResponse.java
  src/main/java/com/dnd/dotchi/domain/card/entity/Card.java
  src/main/java/com/dnd/dotchi/domain/card/repository/CardCustomRepository.java
  src/main/java/com/dnd/dotchi/domain/card/repository/CardCustomRepositoryImpl.java
  src/main/java/com/dnd/dotchi/domain/card/repository/CommentCustomRepository.java
  src/main/java/com/dnd/dotchi/domain/card/repository/CommentCustomRepositoryImpl.java
  src/main/java/com/dnd/dotchi/domain/card/repository/CommentRepository.java
  src/main/java/com/dnd/dotchi/domain/card/service/CardService.java
  src/main/java/com/dnd/dotchi/domain/member/controller/MemberController.java
  src/main/java/com/dnd/dotchi/domain/member/controller/MemberControllerDocs.java
  src/main/java/com/dnd/dotchi/domain/member/entity/Member.java
  src/main/java/com/dnd/dotchi/domain/member/service/MemberService.java
  src/main/resources/data-test.sql
  src/test/java/com/dnd/dotchi/domain/blacklist/controller/BlacklistControllerTest.java
  src/test/java/com/dnd/dotchi/domain/blacklist/service/BlacklistServiceTest.java
  src/test/java/com/dnd/dotchi/domain/card/controller/CardControllerTest.java
  src/test/java/com/dnd/dotchi/domain/card/repository/CardRepositoryTest.java
  src/test/java/com/dnd/dotchi/domain/card/repository/CommentRepositoryTest.java
  src/test/java/com/dnd/dotchi/domain/card/service/CardServiceTest.java
  src/test/java/com/dnd/dotchi/domain/member/controller/MemberControllerTest.java
  src/test/java/com/dnd/dotchi/domain/member/service/MemberServiceTest.java
Labels: 버그

#59 [DEV] 서비스 계층에서 트랜잭션 메서드가 트랜잭션 메서드를 호출하는 코드 수정
  src/main/java/com/dnd/dotchi/domain/card/service/CardService.java
  src/main/java/com/dnd/dotchi/domain/member/service/MemberService.java
Labels: 리팩토링

#61 [DEV] 차단 관련 유저의 데이터는 조회 안되도록 하는 로직 성능 개선
  src/main/java/com/dnd/dotchi/domain/blacklist/repository/BlackListRepository.java
  src/main/java/com/dnd/dotchi/domain/blacklist/service/BlacklistService.java
  src/main/java/com/dnd/dotchi/domain/card/entity/Card.java
  src/main/java/com/dnd/dotchi/domain/card/repository/CardCustomRepository.java
  src/main/java/com/dnd/dotchi/domain/card/repository/CardCustomRepositoryImpl.java
  src/main/java/com/dnd/dotchi/domain/card/repository/CommentCustomRepository.java
  src/main/java/com/dnd/dotchi/domain/card/repository/CommentCustomRepositoryImpl.java
  src/main/java/com/dnd/dotchi/domain/card/service/CardService.java
  src/test/java/com/dnd/dotchi/domain/card/repository/CardRepositoryTest.java
  src/test/java/com/dnd/dotchi/domain/card/repository/CommentRepositoryTest.java
Labels: 개발, 리팩토링

#63 댓글 조회 시, 카드 작성자 프로필 이미지 반환하도록 로직 추가
  src/main/java/com/dnd/dotchi/domain/card/dto/response/CardsResponse.java
  src/main/java/com/dnd/dotchi/domain/card/service/CardService.java
  src/main/resources/application.yml
  src/main/resources/data-prod.sql
Labels: 개발

#64 [DEV] 메인 페이지 차단필터링 적용
  src/main/java/com/dnd/dotchi/domain/card/controller/CardController.java
  src/main/java/com/dnd/dotchi/domain/card/controller/CardControllerDocs.java
  src/main/java/com/dnd/dotchi/domain/card/repository/CardCustomRepository.java
  src/main/java/com/dnd/dotchi/domain/card/repository/CardCustomRepositoryImpl.java
  src/main/java/com/dnd/dotchi/domain/card/repository/CardRepository.java
  src/main/java/com/dnd/dotchi/domain/card/repository/TodayCardCustomRepository.java
  src/main/java/com/dnd/dotchi/domain/card/repository/TodayCardCustomRepositoryImpl.java
  src/main/java/com/dnd/dotchi/domain/card/repository/TodayCardRepository.java
  src/main/java/com/dnd/dotchi/domain/card/service/CardService.java
  src/main/resources/data-test.sql
  src/test/java/com/dnd/dotchi/domain/card/controller/CardControllerTest.java
  src/test/java/com/dnd/dotchi/domain/card/service/CardServiceTest.java
Labels: 개발

#66 테마별 카드 조회에서 각 카드마다 memberImageUrl 응답하도록 로직 추가
  src/main/java/com/dnd/dotchi/domain/card/dto/response/CadsAllResultResponse.java
  src/main/java/com/dnd/dotchi/domain/card/dto/response/CardsByThemeResultResponse.java
  src/main/java/com/dnd/dotchi/domain/card/dto/response/RecentCardsByThemeResponse.java
  src/test/java/com/dnd/dotchi/domain/card/service/CardServiceTest.java
Labels: 개발

#68 [BUG] lastCardCommentCount가 0 이상만 들어오도록 개선
  src/main/java/com/dnd/dotchi/domain/card/dto/request/CardsAllRequest.java
  src/main/java/com/dnd/dotchi/domain/card/dto/request/CardsByThemeRequest.java
  src/test/java/com/dnd/dotchi/domain/card/controller/CardControllerTest.java
Labels: 버그

#70 [BUG] 인기순 조회시, 마지막 카드의 댓글 수와 댓글 수가 같은 카드가 존재할 시 안넘어오는 버그 픽스
  src/main/java/com/dnd/dotchi/domain/card/repository/CardCustomRepositoryImpl.java
  src/test/java/com/dnd/dotchi/domain/card/repository/CardRepositoryTest.java
Labels: 버그
